In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3], dtype = 'int16')
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [8]:
b.shape

(2, 3)

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
#[r, c]
print(a[1, 5])
print(a[1, -2])


13
13


In [24]:
print(a[0, :])
print(a[:, 3])
print(a[0, 1:-1:2])

[1 2 3 4 5 6 7]
[ 4 11]
[2 4 6]


In [26]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((4,2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [34]:
np.full((2,2), 3.14, dtype='int32')

array([[3, 3],
       [3, 3]])

In [36]:
np.random.random_sample(a.shape)

array([[7.44602600e-01, 2.15164709e-02, 3.07338181e-01, 1.85117759e-01,
        5.50494380e-01, 3.53866574e-02, 5.58135504e-01],
       [4.95340083e-01, 1.99429196e-01, 8.02442462e-01, 3.86107196e-01,
        5.84844663e-04, 2.52074978e-01, 6.46741260e-03]])

In [38]:
np.random.rand(4,2)

array([[0.52758125, 0.40339376],
       [0.0656217 , 0.54770445],
       [0.92303322, 0.00230557],
       [0.25178291, 0.10843935]])

In [39]:
np.random.randint(0, 7, size=(3,3))

array([[0, 6, 0],
       [6, 2, 1],
       [4, 0, 0]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 3
print(a)

[1 2 3]
